### ISSUE TITLE
Is this language server specific to VSCode?

### ISSUE THREAD

**Issue by ghost** [IsaacShelton/AdeptVSCodeLanguage#1]
Can I use it with other text editors that support the language server protocol? For example, Sublime Text?

**Comment by IsaacShelton** [comment]
In theory with some modifications yes

The core isn't an LSP protocol language server, but a simple one could be created without too much difficulty probably.

The core is a web assembly binary written in C, you just have to call its `server_main` function with the right JSON and then decode the JSON string it gives back.

(But to create a native LSP you could bypass the whole WASM thing and just include it in a C (or Adept even) project)

https://github.com/IsaacShelton/AdeptInsightNodeJS/tree/master

The general idea of the API can be found [here](https://github.com/IsaacShelton/AdeptInsightNodeJS/blob/master/API.md) although it's not very well documented

**Comment by IsaacShelton** [comment]
I might start I repo to see how easy or hard it would be
